version: '3.2'
services:
  db:
    image: mdillon/postgis:latest
    ports:
      - "5432:5432"
    expose:
      - "5432"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    expose:
      - "6379"